name: ci dockerhub update

on:
  push:
    branches: [ main ]  # Change branch name as needed

jobs:
  build-and-push:
    runs-on: alpine:latest  # Adjust OS as needed
    steps:
      - uses: actions/checkout@v5
        with:
          go-version: '1.22'

      - name: Compiler Protobuf files
        run: make generate-proto

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Login to Docker Hub with secrets
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3  # Build and push image
        with:
          push: true
          tags: glmcz/goapp-grpc-argocd:latest  # Replace with your details