name: ci dockerhub update

on:
  push:
    branches: [ main ]  # Change branch name as needed

jobs:
  deploy:
    runs-on: alpine:latest  # Adjust OS as needed
    steps:
      - uses: actions/checkout@v5
        with:
          go-version: '1.22'

      - name: Compiler Protobuf files
        run: make generate-proto

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@5
        with:
          push: true
          tags: glmcz/goapp-grpc-argocd:tagname